
name: conditional workflows

on:
  push:
    branches:
      - "*"

jobs:
  alwaysrun:
    runs-on: ubuntu-latest
    steps:
      - name: This step always runs
        run: echo "This job runs on every push."

  only-on-main-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: This step runs only on main branch
        run: echo "This job runs only on the main branch."
